### ISSUE TITLE
in Consistency 

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#36]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/a32997ababb028dc8198ec409d40c06817af6970/pythonbetrieb/worksheets/12.md?plain=1#L124

your code is totally correct, nothing wrong with it. 
But please read this artical to understand the important from the "self" 

https://www.knowledgehut.com/blog/programming/self-variabe-python-examples

in your line of code you could exchange "cat" with "self" but try to understand the importance of self in python

**Comment by Max-Wolfram** [comment]
done
