### ISSUE TITLE
your answer is wrong please reconsider

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#40]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/a32997ababb028dc8198ec409d40c06817af6970/pythonbetrieb/worksheets/15.md?plain=1#L81-L96

please try again with this list:  
```python
test_list=[6,-2,-5,3,3] 
```

**Comment by Max-Wolfram** [comment]
done
