### ISSUE TITLE
single quote and double quotes

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#43]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/fa6ae189a4125d93b19c727991907562ad3f1e4a/pythonbetrieb/worksheets/01.md?plain=1#L35-L40

statement line 38 is wrong

this statement 

>  " ist nützlich, wenn man ' in der String und umgekehrt hat 

is correct in its core but you could misunderstand it

**Comment by Max-Wolfram** [comment]
done
