### ISSUE TITLE
not sufficient 

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#45]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/fa6ae189a4125d93b19c727991907562ad3f1e4a/pythonbetrieb/worksheets/05.md?plain=1#L33-L34

in the chapter this are the 3 steps

choose a font
make a stamp
use the stamp

your second answer is not sufficient 

>  Text in Farbe eingeben

i will give you the answer just try to understand

**Comment by Max-Wolfram** [comment]
done
