### ISSUE TITLE
find your own mistake 

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#46]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/fa6ae189a4125d93b19c727991907562ad3f1e4a/pythonbetrieb/worksheets/09.md?plain=1#L65-L72

**Comment by Max-Wolfram** [comment]
ich weiß nicht was daran falsch ist

**Comment by phtrong** [comment]
look at line 70

**Comment by Max-Wolfram** [comment]
wenn du meintest das ich lieber in der range das ergebnis schon beeinflussen soll habe ich es jetzt so angepasst
