### ISSUE TITLE
its looking weird please correct your code/design , the answer are correct

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#47]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/fa6ae189a4125d93b19c727991907562ad3f1e4a/pythonbetrieb/worksheets/09.md?plain=1#L114-L175

here is a picture how it looks on my side
![image](https://user-images.githubusercontent.com/58851170/204761295-edd63a97-7772-4616-84b9-dd0187d1d25a.png)

**Comment by Max-Wolfram** [comment]
done
