### ISSUE TITLE
difference between min_pos and my_list[min_pos]?

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/max-LOGIST#49]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/a32997ababb028dc8198ec409d40c06817af6970/pythonbetrieb/worksheets/17.md?plain=1#L61-L62

**Comment by phtrong** [comment]
https://github.com/T-systemsYoungsters/max-LOGIST/blob/a32997ababb028dc8198ec409d40c06817af6970/pythonbetrieb/worksheets/17.md?plain=1#L61-L66

same mistake !

**Comment by Max-Wolfram** [comment]
done
